import { cn } from "@utils/cn";
import type { Metadata } from "next";
import { Bricolage_Grotesque, DM_Sans } from "next/font/google";
import "./globals.css";

const headingFont = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--heading-font",
  display: "swap",
});

const regularFont = DM_Sans({
  subsets: ["latin"],
  variable: "--regular-font",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(headingFont.variable, regularFont.variable)}
      suppressHydrationWarning
    >
      {children}
    </html>
  );
}
